### ISSUE TITLE
作業ログ

### ISSUE THREAD

**Issue by cnosuke** [k0kubun/isucon5-qualifier#4]
スコアあがった記録

**Comment by cnosuke** [comment]
https://github.com/k0kubun/isucon5-qualifier/commit/ff44b326140630b18e58e1afdf16296d5643470c
https://github.com/cnosuke/isucon5-bootstrap/commit/48b2e50521988812d4730bbd94de1a129837be17

これで200台 => 800台になった

**Comment by k0kubun** [comment]
relationsをone<anotherにして、ちょっとid descいれたら926

**Comment by k0kubun** [comment]
まてぃーのfootprintsインデックス 1192

**Comment by k0kubun** [comment]
cnosukeのばっふぁ 1264

**Comment by k0kubun** [comment]
2947

```
alter table relations add index idx_one(one);
alter table relations add index idx_another(another);
```

**Comment by k0kubun** [comment]
なぜかさがっていて2588

splitやめて
→2632

**Comment by k0kubun** [comment]
friend_ids eager load
6202

**Comment by k0kubun** [comment]
LIMIT10, index, redisチューニング
9557

**Comment by k0kubun** [comment]
LIMIT 1
9610

**Comment by k0kubun** [comment]
N+1
10194

**Comment by k0kubun** [comment]
9907

**Comment by k0kubun** [comment]
再起動
7200

eager_loaded_get_user
→
7963

**Comment by k0kubun** [comment]
もっかいやっただけ
8096

**Comment by k0kubun** [comment]
やっただけ
8195

**Comment by k0kubun** [comment]
やるだけ 8402
